package com.linkedIn.LinkedIn.App.post.entity.enums;

public enum Category {
    JOB,
    EDUCATION,
    TRAINING,
    TECHNOLOGY,
    BUSINESS,
    HEALTHCARE,
    FINANCE,
    MARKETING,
    DESIGN,
    DEVELOPMENT,
    DATA_SCIENCE,
    ENGINEERING,
    MANAGEMENT,
    SALES,
    CUSTOMER_SERVICE,
    HUMAN_RESOURCES,
    LEGAL,
    MEDIA,
    WRITING,
    ENTREPRENEURSHIP,
    PRODUCTIVITY,
    LIFESTYLE,
    LANGUAGES,
    PERSONAL_DEVELOPMENT
}
